name: CI/CD Frontend
on:
  push:
    branches: [main]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ghcr.io
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Lint
        run: cd frontend && npm run lint

      - name: Test
        run: cd frontend && npm test -- --watchAll=false

      - name: Docker Build
        run: docker build -t $DOCKER_REGISTRY/org/frontend:latest ./frontend

      - name: Docker Push
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $DOCKER_REGISTRY -u ${{ github.actor }} --password-stdin
          docker push $DOCKER_REGISTRY/org/frontend:latest

      - name: Deploy to staging
        run: ssh root@${{ secrets.STAGING_IP }} "docker pull $DOCKER_REGISTRY/org/frontend:latest && docker-compose up -d"

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}